import type { Task, UserTask, Proposal, StakingInfo } from "./types";

export const mockTasks: Task[] = [
    {
        id: "1",
        title: "Plant 100 Trees in Urban Areas",
        description:
            "Participate in urban reforestation by planting native trees in designated city zones. Document each tree with GPS coordinates and photos.",
        category: "trees",
        reward: 500,
        proofType: "Photo + GPS",
        status: "active",
        deadline: "2026-06-15",
        participants: 23,
        maxParticipants: 50,
        completedCount: 8,
        createdAt: "2026-03-01",
    },
    {
        id: "2",
        title: "Purchase 10 Tonnes of Carbon Credits",
        description:
            "Buy verified carbon credits from certified providers. Submit purchase receipts and certificate details for verification.",
        category: "carbon",
        reward: 1200,
        proofType: "Receipt + Certificate",
        status: "active",
        deadline: "2026-05-30",
        participants: 12,
        maxParticipants: 30,
        completedCount: 5,
        createdAt: "2026-02-20",
    },
    {
        id: "3",
        title: "Recycle 50kg of Plastic Waste",
        description:
            "Collect and deliver plastic waste to certified recycling centers. Submit weight receipts from the facility.",
        category: "recycling",
        reward: 300,
        proofType: "Weight Receipt",
        status: "active",
        deadline: "2026-04-30",
        participants: 45,
        maxParticipants: 100,
        completedCount: 22,
        createdAt: "2026-02-15",
    },
    {
        id: "4",
        title: "Install Solar Panels for Community Center",
        description:
            "Fund or install solar panels at a community center. Submit installation photos and energy output reports.",
        category: "energy",
        reward: 2000,
        proofType: "Photos + Energy Report",
        status: "active",
        deadline: "2026-07-01",
        participants: 5,
        maxParticipants: 10,
        completedCount: 1,
        createdAt: "2026-03-05",
    },
    {
        id: "5",
        title: "Clean 1km of River Shoreline",
        description:
            "Organize or participate in a river cleanup event. Document before/after photos and waste weight collected.",
        category: "water",
        reward: 400,
        proofType: "Before/After Photos",
        status: "active",
        deadline: "2026-05-15",
        participants: 30,
        maxParticipants: 60,
        completedCount: 15,
        createdAt: "2026-02-28",
    },
    {
        id: "6",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "7",
        title: "E-Waste Collection Drive",
        description:
            "Organize an e-waste collection event in your area. Deliver collected e-waste to certified recyclers.",
        category: "recycling",
        reward: 450,
        proofType: "Collection Records",
        status: "completed",
        deadline: "2026-03-01",
        participants: 40,
        maxParticipants: 40,
        completedCount: 40,
        createdAt: "2026-01-15",
    },
    {
        id: "8",
        title: "Plant a Community Garden 2",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "9",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "10",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "11",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "12",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
    {
        id: "13",
        title: "Plant a Community Garden",
        description:
            "Establish a community garden in your neighborhood. Document the setup process, plant species, and community involvement.",
        category: "trees",
        reward: 350,
        proofType: "Photo Series + Plan",
        status: "active",
        deadline: "2026-06-01",
        participants: 18,
        maxParticipants: 25,
        completedCount: 3,
        createdAt: "2026-03-08",
    },
];

export const mockUserTasks: UserTask[] = [
    {
        id: "ut-1",
        task: mockTasks[0],
        status: "approved",
        proofUrl: "https://example.com/proof/1",
        submittedAt: "2026-03-10",
        earnedRN: 500,
        txHash: "0.0.12345",
    },
    {
        id: "ut-2",
        task: mockTasks[2],
        status: "pending_verification",
        proofUrl: "https://example.com/proof/2",
        submittedAt: "2026-03-09",
        earnedRN: 0,
    },
    {
        id: "ut-3",
        task: mockTasks[4],
        status: "joined",
        earnedRN: 0,
    },
    {
        id: "ut-4",
        task: mockTasks[6],
        status: "approved",
        proofUrl: "https://example.com/proof/4",
        submittedAt: "2026-02-28",
        earnedRN: 450,
        txHash: "0.0.67890",
    },
];

export const mockProposals: Proposal[] = [
    {
        id: "p-1",
        title: "Verify: Plant 100 Trees - Volunteer #12",
        type: "task_verification",
        description:
            "Review the proof submitted by volunteer #12 for the urban tree planting task. GPS data and photos provided.",
        status: "active",
        votingEnds: "2026-03-20",
        yesVotes: 45,
        noVotes: 12,
        totalVoters: 57,
        taskProof: {
            taskTitle: "Plant 100 Trees in Urban Areas",
            volunteer: "0x1234...5678",
            proofUrl: "https://example.com/proof/12",
        },
    },
    {
        id: "p-2",
        title: "Verify: Carbon Credits Purchase - Volunteer #8",
        type: "task_verification",
        description:
            "Review the receipt and certificate for 10 tonnes of carbon credits purchased by volunteer #8.",
        status: "active",
        votingEnds: "2026-03-22",
        yesVotes: 30,
        noVotes: 5,
        totalVoters: 35,
        taskProof: {
            taskTitle: "Purchase 10 Tonnes of Carbon Credits",
            volunteer: "0xabcd...ef01",
            proofUrl: "https://example.com/proof/8",
        },
    },
    {
        id: "p-3",
        title: "Increase Recycling Task Reward to 400 RN",
        type: "parameter_change",
        description:
            "Proposal to increase the reward for the 50kg plastic recycling task from 300 RN to 400 RN to incentivize more participation.",
        status: "active",
        votingEnds: "2026-03-25",
        yesVotes: 65,
        noVotes: 20,
        totalVoters: 85,
    },
    {
        id: "p-4",
        title: "Verify: River Cleanup - Volunteer #22",
        type: "task_verification",
        description:
            "Before and after photos submitted for the 1km river cleanup. Community event with 15 participants.",
        status: "passed",
        votingEnds: "2026-03-10",
        yesVotes: 80,
        noVotes: 8,
        totalVoters: 88,
        taskProof: {
            taskTitle: "Clean 1km of River Shoreline",
            volunteer: "0x9876...4321",
            proofUrl: "https://example.com/proof/22",
        },
    },
    {
        id: "p-5",
        title: "Reduce Minimum Stake to 50 RN",
        type: "parameter_change",
        description:
            "Lower the minimum staking requirement from 100 RN to 50 RN to allow broader participation in governance.",
        status: "rejected",
        votingEnds: "2026-03-08",
        yesVotes: 25,
        noVotes: 60,
        totalVoters: 85,
    },
];

export const mockStakingInfo: StakingInfo = {
    stakedRN: 2500,
    votingPower: 50,
    rewards: 125,
    apy: 12.5,
};
